apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: wishlist-app
  template:
    metadata:
      labels: 
        component: wishlist-app
    spec:
      containers:
      - name: wishlist-app-container
        image: tharun13055/user-wishlist-k8s:v1
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: '6379'
        - name: POSTGRES_USER
          value: hello_flask
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_DB
          value: hello_flask_db
        - name: POSTGRES_PASSWORD
          valueFrom:
             secretKeyRef:
              name: my-secret
              key: password


      